### ISSUE TITLE
¡Hola! Un error al importar...

### ISSUE THREAD

**Issue by Snoop13** [silvelo/raspbot#2]
Hola me da un error al ejecutar, 

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from telebot import util
ImportError: cannot import name util

**Comment by silvelo** [comment]
Tienes instalada la libreria [telebot](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/util.py) , ya que parece ser que no encuentra ese fichero.

**Comment by Snoop13** [comment]
Hola, si gracias ¿Tienes telegram? o algun otro lado para hablar?

**Comment by silvelo** [comment]
Doy por cerrada esta issue.

**Comment by silvelo** [comment]
He creado un chat en gitter, #3

**Comment by silvelo** [comment]
Creado chat gitter. close #3

**Comment by silvelo** [comment]
Creado chat gitter. closed #3

**Comment by silvelo** [comment]
He creado un gitter #3
